// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRGb-Eu_YqWhwx08q_Qam6hmEYlr9PRb0',
    appId: '1:112155694163:web:9183921d66f02d92bba2a6',
    messagingSenderId: '112155694163',
    projectId: 'subcript-ddf01',
    authDomain: 'subcript-ddf01.firebaseapp.com',
    storageBucket: 'subcript-ddf01.firebasestorage.app',
    measurementId: 'G-CZV36GXHPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGP3N1qal2SWag9CHOmFb8bnFOBPMtg34',
    appId: '1:112155694163:android:1e3ed0ff51786112bba2a6',
    messagingSenderId: '112155694163',
    projectId: 'subcript-ddf01',
    storageBucket: 'subcript-ddf01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg9Zk6UxbaYoSVl9yJlLCwYaFm1yP5mA8',
    appId: '1:112155694163:ios:5280258e14a88acdbba2a6',
    messagingSenderId: '112155694163',
    projectId: 'subcript-ddf01',
    storageBucket: 'subcript-ddf01.firebasestorage.app',
    iosBundleId: 'com.subcriptio.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg9Zk6UxbaYoSVl9yJlLCwYaFm1yP5mA8',
    appId: '1:112155694163:ios:4a3c03e3f2e20dcabba2a6',
    messagingSenderId: '112155694163',
    projectId: 'subcript-ddf01',
    storageBucket: 'subcript-ddf01.firebasestorage.app',
    iosBundleId: 'com.subcript.subcriptFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRGb-Eu_YqWhwx08q_Qam6hmEYlr9PRb0',
    appId: '1:112155694163:web:57833c42b10c6c59bba2a6',
    messagingSenderId: '112155694163',
    projectId: 'subcript-ddf01',
    authDomain: 'subcript-ddf01.firebaseapp.com',
    storageBucket: 'subcript-ddf01.firebasestorage.app',
    measurementId: 'G-YBV08MT20M',
  );
}
